//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.BookEditorServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Books", Namespace="http://schemas.datacontract.org/2004/07/BookEditor", ItemName="BookData")]
    [System.SerializableAttribute()]
    public class Books : System.Collections.Generic.List<StoreApp.BookEditorServices.BookData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class BookData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StoreApp.BookEditorServices.LoginResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : StoreApp.BookEditorServices.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Orders", Namespace="http://schemas.datacontract.org/2004/07/BookEditor", ItemName="OrderData")]
    [System.SerializableAttribute()]
    public class Orders : System.Collections.Generic.List<StoreApp.BookEditorServices.OrderData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class OrderData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long book_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string book_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string client_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string state_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long book_id {
            get {
                return this.book_idField;
            }
            set {
                if ((this.book_idField.Equals(value) != true)) {
                    this.book_idField = value;
                    this.RaisePropertyChanged("book_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string book_title {
            get {
                return this.book_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.book_titleField, value) != true)) {
                    this.book_titleField = value;
                    this.RaisePropertyChanged("book_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client_email {
            get {
                return this.client_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.client_emailField, value) != true)) {
                    this.client_emailField = value;
                    this.RaisePropertyChanged("client_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((this.client_idField.Equals(value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state_date {
            get {
                return this.state_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.state_dateField, value) != true)) {
                    this.state_dateField = value;
                    this.RaisePropertyChanged("state_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Requests", Namespace="http://schemas.datacontract.org/2004/07/BookEditor", ItemName="RequestData")]
    [System.SerializableAttribute()]
    public class Requests : System.Collections.Generic.List<StoreApp.BookEditorServices.RequestData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class RequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long book_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string state_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long book_id {
            get {
                return this.book_idField;
            }
            set {
                if ((this.book_idField.Equals(value) != true)) {
                    this.book_idField = value;
                    this.RaisePropertyChanged("book_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state_date {
            get {
                return this.state_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.state_dateField, value) != true)) {
                    this.state_dateField = value;
                    this.RaisePropertyChanged("state_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StoreApp.BookEditorServices.RegisterData))]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class RegisterData : StoreApp.BookEditorServices.LoginData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutData", Namespace="http://schemas.datacontract.org/2004/07/BookEditor")]
    [System.SerializableAttribute()]
    public partial class LogoutData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookEditorServices.IServiceAuth")]
    public interface IServiceAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/login", ReplyAction="http://tempuri.org/IServiceAuth/loginResponse")]
        StoreApp.BookEditorServices.LoginResponse login(StoreApp.BookEditorServices.LoginData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/login", ReplyAction="http://tempuri.org/IServiceAuth/loginResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.LoginResponse> loginAsync(StoreApp.BookEditorServices.LoginData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/logout", ReplyAction="http://tempuri.org/IServiceAuth/logoutResponse")]
        StoreApp.BookEditorServices.Response logout(StoreApp.BookEditorServices.LogoutData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/logout", ReplyAction="http://tempuri.org/IServiceAuth/logoutResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> logoutAsync(StoreApp.BookEditorServices.LogoutData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/register", ReplyAction="http://tempuri.org/IServiceAuth/registerResponse")]
        StoreApp.BookEditorServices.Response register(StoreApp.BookEditorServices.RegisterData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuth/register", ReplyAction="http://tempuri.org/IServiceAuth/registerResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> registerAsync(StoreApp.BookEditorServices.RegisterData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAuthChannel : StoreApp.BookEditorServices.IServiceAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAuthClient : System.ServiceModel.ClientBase<StoreApp.BookEditorServices.IServiceAuth>, StoreApp.BookEditorServices.IServiceAuth {
        
        public ServiceAuthClient() {
        }
        
        public ServiceAuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreApp.BookEditorServices.LoginResponse login(StoreApp.BookEditorServices.LoginData data) {
            return base.Channel.login(data);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.LoginResponse> loginAsync(StoreApp.BookEditorServices.LoginData data) {
            return base.Channel.loginAsync(data);
        }
        
        public StoreApp.BookEditorServices.Response logout(StoreApp.BookEditorServices.LogoutData data) {
            return base.Channel.logout(data);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> logoutAsync(StoreApp.BookEditorServices.LogoutData data) {
            return base.Channel.logoutAsync(data);
        }
        
        public StoreApp.BookEditorServices.Response register(StoreApp.BookEditorServices.RegisterData data) {
            return base.Channel.register(data);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> registerAsync(StoreApp.BookEditorServices.RegisterData data) {
            return base.Channel.registerAsync(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookEditorServices.IServiceStore", CallbackContract=typeof(StoreApp.BookEditorServices.IServiceStoreCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServiceStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getBooks", ReplyAction="http://tempuri.org/IServiceStore/getBooksResponse")]
        StoreApp.BookEditorServices.Books getBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getBooks", ReplyAction="http://tempuri.org/IServiceStore/getBooksResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Books> getBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/addBook", ReplyAction="http://tempuri.org/IServiceStore/addBookResponse")]
        StoreApp.BookEditorServices.Response addBook(StoreApp.BookEditorServices.BookData book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/addBook", ReplyAction="http://tempuri.org/IServiceStore/addBookResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> addBookAsync(StoreApp.BookEditorServices.BookData book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/updateBook", ReplyAction="http://tempuri.org/IServiceStore/updateBookResponse")]
        StoreApp.BookEditorServices.Response updateBook(StoreApp.BookEditorServices.BookData book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/updateBook", ReplyAction="http://tempuri.org/IServiceStore/updateBookResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> updateBookAsync(StoreApp.BookEditorServices.BookData book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/sellBook", ReplyAction="http://tempuri.org/IServiceStore/sellBookResponse")]
        StoreApp.BookEditorServices.Response sellBook(StoreApp.BookEditorServices.BookData book, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/sellBook", ReplyAction="http://tempuri.org/IServiceStore/sellBookResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> sellBookAsync(StoreApp.BookEditorServices.BookData book, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/orderBook", ReplyAction="http://tempuri.org/IServiceStore/orderBookResponse")]
        StoreApp.BookEditorServices.Response orderBook(StoreApp.BookEditorServices.BookData book, long quantity, string clientName, string clientEmail, string clientPassowrd, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/orderBook", ReplyAction="http://tempuri.org/IServiceStore/orderBookResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> orderBookAsync(StoreApp.BookEditorServices.BookData book, long quantity, string clientName, string clientEmail, string clientPassowrd, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getOrders", ReplyAction="http://tempuri.org/IServiceStore/getOrdersResponse")]
        StoreApp.BookEditorServices.Orders getOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getOrders", ReplyAction="http://tempuri.org/IServiceStore/getOrdersResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Orders> getOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getRequests", ReplyAction="http://tempuri.org/IServiceStore/getRequestsResponse")]
        StoreApp.BookEditorServices.Requests getRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/getRequests", ReplyAction="http://tempuri.org/IServiceStore/getRequestsResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Requests> getRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/ReceivedRequest", ReplyAction="http://tempuri.org/IServiceStore/ReceivedRequestResponse")]
        StoreApp.BookEditorServices.Response ReceivedRequest(StoreApp.BookEditorServices.RequestData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStore/ReceivedRequest", ReplyAction="http://tempuri.org/IServiceStore/ReceivedRequestResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> ReceivedRequestAsync(StoreApp.BookEditorServices.RequestData request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStoreCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceStore/UpdateOrders")]
        void UpdateOrders();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStoreChannel : StoreApp.BookEditorServices.IServiceStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStoreClient : System.ServiceModel.DuplexClientBase<StoreApp.BookEditorServices.IServiceStore>, StoreApp.BookEditorServices.IServiceStore {
        
        public ServiceStoreClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStoreClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public StoreApp.BookEditorServices.Books getBooks() {
            return base.Channel.getBooks();
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Books> getBooksAsync() {
            return base.Channel.getBooksAsync();
        }
        
        public StoreApp.BookEditorServices.Response addBook(StoreApp.BookEditorServices.BookData book) {
            return base.Channel.addBook(book);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> addBookAsync(StoreApp.BookEditorServices.BookData book) {
            return base.Channel.addBookAsync(book);
        }
        
        public StoreApp.BookEditorServices.Response updateBook(StoreApp.BookEditorServices.BookData book) {
            return base.Channel.updateBook(book);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> updateBookAsync(StoreApp.BookEditorServices.BookData book) {
            return base.Channel.updateBookAsync(book);
        }
        
        public StoreApp.BookEditorServices.Response sellBook(StoreApp.BookEditorServices.BookData book, int quantity) {
            return base.Channel.sellBook(book, quantity);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> sellBookAsync(StoreApp.BookEditorServices.BookData book, int quantity) {
            return base.Channel.sellBookAsync(book, quantity);
        }
        
        public StoreApp.BookEditorServices.Response orderBook(StoreApp.BookEditorServices.BookData book, long quantity, string clientName, string clientEmail, string clientPassowrd, string address) {
            return base.Channel.orderBook(book, quantity, clientName, clientEmail, clientPassowrd, address);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> orderBookAsync(StoreApp.BookEditorServices.BookData book, long quantity, string clientName, string clientEmail, string clientPassowrd, string address) {
            return base.Channel.orderBookAsync(book, quantity, clientName, clientEmail, clientPassowrd, address);
        }
        
        public StoreApp.BookEditorServices.Orders getOrders() {
            return base.Channel.getOrders();
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Orders> getOrdersAsync() {
            return base.Channel.getOrdersAsync();
        }
        
        public StoreApp.BookEditorServices.Requests getRequests() {
            return base.Channel.getRequests();
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Requests> getRequestsAsync() {
            return base.Channel.getRequestsAsync();
        }
        
        public StoreApp.BookEditorServices.Response ReceivedRequest(StoreApp.BookEditorServices.RequestData request) {
            return base.Channel.ReceivedRequest(request);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> ReceivedRequestAsync(StoreApp.BookEditorServices.RequestData request) {
            return base.Channel.ReceivedRequestAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookEditorServices.IServiceWarehouse", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServiceWarehouse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWarehouse/ship", ReplyAction="http://tempuri.org/IServiceWarehouse/shipResponse")]
        StoreApp.BookEditorServices.Response ship(StoreApp.BookEditorServices.RequestData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWarehouse/ship", ReplyAction="http://tempuri.org/IServiceWarehouse/shipResponse")]
        System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> shipAsync(StoreApp.BookEditorServices.RequestData request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWarehouseChannel : StoreApp.BookEditorServices.IServiceWarehouse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWarehouseClient : System.ServiceModel.ClientBase<StoreApp.BookEditorServices.IServiceWarehouse>, StoreApp.BookEditorServices.IServiceWarehouse {
        
        public ServiceWarehouseClient() {
        }
        
        public ServiceWarehouseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWarehouseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWarehouseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWarehouseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreApp.BookEditorServices.Response ship(StoreApp.BookEditorServices.RequestData request) {
            return base.Channel.ship(request);
        }
        
        public System.Threading.Tasks.Task<StoreApp.BookEditorServices.Response> shipAsync(StoreApp.BookEditorServices.RequestData request) {
            return base.Channel.shipAsync(request);
        }
    }
}
